version: '3.8'

services:
    frontend-arena:
        image: nginx:alpine
        volumes:
            - ./frontend_arena/:/usr/share/nginx/html/
        ports:
            - "3000:80"

    backend-arena:
        build:
            context: ./arena
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            - RUST_LOG=debug
            - RUST_BACKTRACE=1
            - RUST_BACKTRACE=full
        networks:
            - arena-network

    python-player:
        build:
            context: ./python_player_template
            dockerfile: Dockerfile
        environment:
            - ARENA_HOST=backend-arena
            - ARENA_PORT=8080
            - PLAYER_NAME=PythonPlayer
        networks:
            - arena-network
        depends_on:
            - backend-arena

    php-player:
        build:
            context: ./php_player_template
            dockerfile: Dockerfile
        environment:
            - ARENA_HOST=backend-arena
            - ARENA_PORT=8080
            - PLAYER_NAME=PHPPlayer
        networks:
            - arena-network
        depends_on:
            - backend-arena

networks:
    arena-network:
        external: true
