version: '3.8'

services:
    filler_arena:
        build:
            context: .
            dockerfile: Dockerfile_arena
        container_name: arena
        ports:
            - "8765:8765"
        volumes:
            - play_zone:/tmp
        environment:
            - ARENA_PATH=/tmp
            - PLAYER1=Player1
            - PLAYER2=Player2
            - BOARD_SIZE=42
            - PIECE_SIZE=5
            - PIECE_DENSITY=3
        command: sh -c "
            python -u -m filler_arena.command.run \
                --arena_path $${ARENA_PATH} --player1 $${PLAYER1} \
                --player2 $${PLAYER2} --board_size $${BOARD_SIZE} \
                --piece_size $${PIECE_SIZE} \
                --piece_density $${PIECE_DENSITY}"
        depends_on:
            - player1
            - player2

    player1:
        build:
            context: .
            dockerfile: Dockerfile_python
        container_name: player1
        environment:
            - PLAYER_NAME=Player1
        volumes:
            - play_zone:/tmp
        env_file:
            - env_file.env

    player2:
        build:
            context: .
            dockerfile: Dockerfile_python0
        container_name: player2
        environment:
            - PLAYER_NAME=Player2
        volumes:
            - play_zone:/tmp
        env_file:
            - env_file.env

volumes:
    play_zone:
