version: '3.8'

services:
    arena:
        build:
            context: ./arena
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        expose:
            - "0.0.0.0:8080"
        environment:
            - RUST_LOG=debug
            - RUST_BACKTRACE=1
            - RUST_BACKTRACE=full
        networks:
            - arena-network

    python_player_template:
        build:
            context: ./python_player_template
            dockerfile: Dockerfile
        environment:
            - ARENA_HOST=arena
            - ARENA_PORT=8080
            - PLAYER_NAME=PythonPlayerTemplate
        networks:
            - arena-network
        depends_on:
            - arena
    python_player_template2:
        build:
            context: ./python_player_template
            dockerfile: Dockerfile
        environment:
            - ARENA_HOST=arena
            - ARENA_PORT=8080
            - PLAYER_NAME=PythonPlayerTemplate2
        networks:
            - arena-network
        depends_on:
            - arena

networks:
    arena-network:
        driver: bridge
