version: '3.8'

services:
    arena:
        build:
            context: ./arena
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        expose:
            - "0.0.0.0:8080"
        environment:
            - RUST_LOG=debug
            - RUST_BACKTRACE=1
            - RUST_BACKTRACE=full
        networks:
            - arena-network

    python_player:
        build:
            context: ./python_player_template
            dockerfile: Dockerfile
        environment:
            - ARENA_HOST=arena
            - ARENA_PORT=8080
            - PLAYER_NAME=PythonPlayer
        networks:
            - arena-network
        depends_on:
            - arena

    python_player2:
        build:
            context: ./python_player_template
            dockerfile: Dockerfile
        environment:
            - ARENA_HOST=arena
            - ARENA_PORT=8080
            - PLAYER_NAME=PythonPlayer
        networks:
            - arena-network
        depends_on:
            - arena

    python_player3:
        build:
            context: ./python_player_template
            dockerfile: Dockerfile
        environment:
            - ARENA_HOST=arena
            - ARENA_PORT=8080
            - PLAYER_NAME=PythonPlayer
        networks:
            - arena-network
        depends_on:
            - arena
    # php_player:
    #     build:
    #         context: ./php_player_template
    #         dockerfile: Dockerfile
    #     environment:
    #         - ARENA_HOST=arena
    #         - ARENA_PORT=8080
    #         - PLAYER_NAME=PHPPlayer
    #     networks:
    #         - arena-network
    #     depends_on:
    #         - arena

networks:
    arena-network:
        external: true
