version: '3.8'

services:

    python_player_template:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - ARENA_HOST=arena
            - ARENA_PORT=8080
            - PLAYER_NAME=PythonPlayerTemplate
        volumes:
            - .:.
        networks:
            - arena-network

networks:
    arena-network:
        external: true
